name: Static Analysis
on:
  pull_request:
  push:
  workflow_dispatch:
# Adapted from https://stackoverflow.com/a/72408109
concurrency:
  group: ${{github.workflow}}-${{github.event.pull_request.number || github.ref}}
  cancel-in-progress: true
jobs:
  support_files:
    name: Support Files
    uses: brobeson/SupportFileQuality/.github/workflows/support_files.yaml@v1
  build:
    name: C++ Builds
    uses: brobeson/CppWorkflow/.github/workflows/build_all_the_things.yaml@v1
    with:
      configure-definitions: -D CppStarter_DEV_BUILD:BOOL=on
  static_analysis:
    name: C++ Code Quality
    uses: brobeson/CppWorkflow/.github/workflows/cpp_static_analysis.yaml@main
    with:
      configure-definitions: -D CppStarter_DEV_BUILD:BOOL=on
