# cspell:words pathspec
name: New Project Setup
on:
  workflow_dispatch:
    inputs:
      description:
        description: 'The short description of your new project.'
        required: true
        type: string
jobs:
  tidy:
    name: Customize
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - run: echo "${{inputs.description}}"
